// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQQx9Bv7bUGLIXl2SO1RuGFwmVZqFUTag',
    appId: '1:443207504457:web:50330e0732548361262598',
    messagingSenderId: '443207504457',
    projectId: 'financas-inteligentes-b67db',
    authDomain: 'financas-inteligentes-b67db.firebaseapp.com',
    storageBucket: 'financas-inteligentes-b67db.firebasestorage.app',
    measurementId: 'G-D4K1VZ2YR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjs-X7Sb7quhJFBM4xJKoPi5wYEdGQo38',
    appId: '1:443207504457:android:73b49ea0f852035c262598',
    messagingSenderId: '443207504457',
    projectId: 'financas-inteligentes-b67db',
    storageBucket: 'financas-inteligentes-b67db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGxWWMht_juh8zacZ8P-f2te3mvI8VF8o',
    appId: '1:443207504457:ios:ed845b0f59fbd4b4262598',
    messagingSenderId: '443207504457',
    projectId: 'financas-inteligentes-b67db',
    storageBucket: 'financas-inteligentes-b67db.firebasestorage.app',
    iosClientId: '443207504457-9nd51tdnubbknsi42vfbhtb2fak5vfrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.financasInteligentes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGxWWMht_juh8zacZ8P-f2te3mvI8VF8o',
    appId: '1:443207504457:ios:ed845b0f59fbd4b4262598',
    messagingSenderId: '443207504457',
    projectId: 'financas-inteligentes-b67db',
    storageBucket: 'financas-inteligentes-b67db.firebasestorage.app',
    iosClientId: '443207504457-9nd51tdnubbknsi42vfbhtb2fak5vfrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.financasInteligentes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQQx9Bv7bUGLIXl2SO1RuGFwmVZqFUTag',
    appId: '1:443207504457:web:50330e0732548361262598',
    messagingSenderId: '443207504457',
    projectId: 'financas-inteligentes-b67db',
    authDomain: 'financas-inteligentes-b67db.firebaseapp.com',
    storageBucket: 'financas-inteligentes-b67db.firebasestorage.app',
    measurementId: 'G-D4K1VZ2YR8',
  );

}